apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-nav-oppdrag
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi
  ingresses:
    - https://sokos-nav-oppdrag.intern.nav.no
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
  webproxy: true
  env:
    - name: USE_AUTHENTICATION
      value: "true"