apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-nav-oppdrag
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi
  ingresses:
    - https://sokos-nav-oppdrag.dev.intern.nav.no
    - https://sokos-nav-oppdrag.dev-fss-pub.nais.io
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: sokos-op-fasade
          namespace: okonomi
          cluster: dev-gcp
  webproxy: true
  envFrom:
    - secret: oppdrag-credentials
  filesFrom:
    - secret: db2license
      mountPath: /var/run/secrets/db2license
  env:
    - name: DATABASE_HOST
      value: "155.55.1.82"
    - name: DATABASE_PORT
      value: "5025"
    - name: DATABASE_NAME
      value: "QDB2"
    - name: DATABASE_SCHEMA
      value: "OS231Q1"
    - name: USE_AUTHENTICATION
      value: "true"