openapi: '3.0.3'

info:
  version: 1.0.0
  title: OppdragsInfo API (sokos-nav-oppdrag)
  description: API-tjeneste for å hente og presentere oppdragsinformasjon tilknyttet person eller foretak
  contact:
    name: PO Utbetaling
    email: okonomi@nav.no
    url: https://nav-it.slack.com/archives/CKZADNFBP

tags:
  - name: oppdragsinfo
    description: Opplysninger om oppdrag tilknyttet person eller foretak

servers:
  - url: /api/v1/oppdragsinfo


paths:
  /oppdrag:
    post:
      tags:
        - oppdragsinfo
      summary: Søk etter oppdragsinfo
      description: Returnerer oppdragsopplysninger tilknyttet person eller foretak.
      operationId: sokOppdrag
      requestBody:
        description: (gjelderId) er et krav, men (fagGruppeKode) er alternativ hvis filtrering er ønskelig.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SokOppdragRequest'
        required: true
      responses:
        200:
          description: OK - Hvis oppdrag ikke finnes, returneres tom liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SokOppdragResponse'
        400:
          description: Ugyldig request, oppfyller ikke swagger-kontrakt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        401:
          description: Ingen tilgang
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      security:
        - Bearer: [ ]


  /faggrupper:
    get:
      tags:
        - oppdragsinfo
      summary: Hent tilgjengelige faggrupper
      description: Returnerer en liste av tilgjengelige faggrupper. Faggruppe kan brukes til å filtrere søket i endepunktet -> /oppdrag
      operationId: hentFagGrupper
      responses:
        200:
          description: OK - Hvis faggrupper ikke finnes så returneres tom liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FagGruppe'

      security:
        - Bearer: [ ]

  /{oppdragsId}:
    post:
      tags:
        - oppdragsinfo
      summary: Hent oppdrag
      description: Returnerer oppdrag med tilhørende oppdragslinjer spesifisert av oppdragsId.
      operationId: hentOppdrag
      parameters:
        - name: oppdragsId
          in: path
          description: Oppdrags id
          required: true
          schema:
            type: string
      requestBody:
        description: (gjelderId) er et krav og eneste verdi som skal sendes inn. Faggruppekode ikke relevant.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GjelderIdRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OppdragsResponse'
        400:
          description: Ugyldig request - Oppdragsid har ingen tilknytning til gjelderId
        401:
          description: Ingen tilgang
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

      security:
        - Bearer: [ ]

components:
  schemas:

    SokOppdragRequest:
      type: object
      required:
        - gjelderId
      properties:
        gjelderId:
          type: string
          example: "9 eller 11 siffer"
          description: 9 eller 11 siffer
        fagGruppeKode:
          type: string
          description: filtrering på faggruppeKode

    GjelderIdRequest:
      type: object
      required:
        - gjelderId
      properties:
        gjelderId:
          type: string
          example: "9 eller 11 siffer"
          description: 9 eller 11 siffer

    SokOppdragResponse:
      type: object
      properties:
        gjelderId:
          type: string
        gjelderNavn:
          type: string
        oppdragsListe:
          type: array
          items:
            $ref: '#/components/schemas/Oppdrag'

    OppdragsResponse:
      type: object
      required:
        - enhet
        - harOmposteringer
        - oppdragsLinjer
      properties:
        enhet:
          $ref: '#/components/schemas/OppdragsEnhet'
        behandlendeEnhet:
          $ref: '#/components/schemas/OppdragsEnhet'
        harOmposteringer:
          type: boolean
          description: Spesifiserer om oppdraget har omposteringer i samme faggruppe som oppdraget
        oppdragsLinjer:
          type: array
          items:
            $ref: '#/components/schemas/OppdragsLinje'

    Oppdrag:
      type: object
      properties:
        fagsystemId:
          type: string
        oppdragsId:
          type: integer
        navnFagGruppe:
          type: string
        navnFagOmraade:
          type: string
        kjorIdag:
          type: string
        typeBilag:
          type: string
        kodeStatus:
          type: string

    OppdragsEnhet:
      type: object
      properties:
        type:
          type: string
        datoFom:
          type: string
        enhet:
          type: string

    OppdragsLinje:
      type: object
      required:
        - linjeId
        - kodeKlasse
        - datoVedtakFom
        - sats
        - typeSats
        - datoFom
        - delytelseId
        - utbetalesTilId
        - brukerId
        - tidspktReg
      properties:
        linjeId:
          type: integer
        kodeKlasse:
          type: string
        datoVedtakFom:
          type: string
        datoVedtakTom:
          type: string
        sats:
          type: number
          format: double
        typeSats:
          type: string
        kodeStatus:
          type: string
        datoFom:
          type: string
        linjeIdKorr:
          type: integer
        attestert:
          type: string
        delytelseId:
          type: string
        utbetalesTilId:
          type: string
        refunderesOrgnr:
          type: string
        brukerId:
          type: string
        tidspktReg:
          type: string

    FagGruppe:
      type: object
      properties:
        navn:
          type: string
        type:
          type: string

    ApiError:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
          description: Tidspunkt feilen oppsto
        status:
          type: integer
          example: 4xx
          description: HTTP status kode
        error:
          type: string
          example: Bad Request
          description: En kort, lesbar oppsummering av problemet
        message:
          type: string
          example: Verdien er ikke tilatt
          description: En lesbar forklaring som er spesifikk for denne forekomsten av problemet
        path:
          type: string
          example: /api/v1/oppdragsinfo/oppdrag
          description: Endepunktet hvor feilen oppstå

  securitySchemes:
    Bearer:
      type: apiKey
      description: |-
        OBO-token (JWT via OAuth2.0).<br> 
          Følgende format må brukes i input-feltet "Value" under: <strong>\"Bearer {token}\"</strong>.<br> 
          Eksempel på verdi i input-felt: <strong>Bearer eYdmifml0ejugm</strong>
      name: Authorization
      in: header